// Code generated by Slice Machine. DO NOT EDIT.

import People from './People';
import TextSection from './TextSection';

export {
	People,
	TextSection,
};

export const components = {
	people: People,
	text_section: TextSection,
};
