// Code generated by Slice Machine. DO NOT EDIT.

import LogoSlider from './LogoSlider';
import People from './People';
import Section from './Section';
import TextSection from './TextSection';

export {
	LogoSlider,
	People,
	Section,
	TextSection,
};

export const components = {
	logo_slider: LogoSlider,
	people: People,
	section: Section,
	text_section: TextSection,
};
